language: node_js
node_js:
- '7'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: Bv7/vVvZhLe+voMtrjMbxmM8d4bM1F4asYfUEreRiFeLeuys9F6sfE6gTHcWcnGGHET3Z8KN+Tr0rRxkcuVP41zdMl24LZxeI31RWQYdLdp6mn+rZ9qFKLlaSlfESQ0DGB4JvZKVwE3XRWjJdcA+v5rYtFs686eseMyXihqzJhBGwlCRo+BqzRbpHjuuqPXFNmdhVAn+Io0lWV8zo2FhOY6A4EQbaT5W9ocOC4o3BKow4NyYIXbOp8hQwrZRyM+52KUVkCEP0veOCVXJ1TUit0FjcrN3qPjy3K2cSghIepkt6ZPE7fmNL8k0IETVhHu8pIXUt1rRKMfycwj53NcHqh4OpQ4tZ4htFc4Erv43T3PNgjcAkiQDAxCn/kTlfdmQEDIyMrEESmHpmaSR6732eLnOsqeGbP+6zT7lcK5bAcLxQuu1Km7A7ZGo+o9yk8uL/R3gt+URW4O1Wxjjgy6JpzwIqS+u1WRhectpdyLgg5LKcYcoN+l3JOPQuSCw9FU+DolOTi4u3xk2abb/lmzN4uS73ILbskf/ylt54bd7EBIj6KvWl+gwmIxt8/B2/PmumPR31hRkxlRobEdw3sXagnxSpUXrImz9y30wL00fa/gkItfPxt0g/gIGrm+iAhsi4J/ZnO1qUQ7ndPdowTkj1vn+eBzeRmISAaOTZg1pdns=
deploy:
  provider: npm
  email: deptno@gmail.com
  api_key:
    secure: E4nKSbJK5HA2rtJpjst4FsBKTzqhpjAy+5BF7l/KBTXfPwTDAyLl5xUi0S8nemXrk+oglm8CBZeauh8Wh+vuAO1pj5HpfAwJaNe4AURMn+hZjrGElPUQQ0WTsKwA7jzKvXYA0N/gKmk1azqQK/972J5zIHJ4U34BMQsOE9SlmG/H9mgv7eZm3pIlhKDeWSAf8IuGvn0Fw3/neayQChPRXS7LdCDHsJBojW2DKiOCDHixUT2OvSlokRNr8A/NG//7Je4sd9/baz1GjUp9QQUH4XPxV8Q3v8zae3DsUSyUMpKNcGfAoOgtG+aa/zr7W/aJcrJX+paZ0URk+lSwSVFKEsc5KTSoBP0ui+/OzHysonWIeeB6ZTdcI5SawL0FNjhWdwR/AMKp8VXVqLJrkJfLm2ojS4swFBkuejKuEToi+1vAf7F1nZXl0/CvKWXF7k3FZODeHXmZ9psQ+0og85rqvjbaAVbUXhUTL4VLJM7E+gYsEdMy+C4/taUXtZu3S373v+vDXCxdbdZe3bbkTC4aT8xHBqiWUycHwGrAhW1y30OG7lc6F6WRDrPMi9SLhCkpKqBJj0LE4dSCJu9iA5s6NHZ3azd+iS0epL2mAUNfvJJs9v3Q9OhsK5O0dh29qUEAzm0XkyanWSw0S+t6KxS5G0WcVdBiL9YMgqs6z9xnKwM=
