language: node_js
node_js:
- '7'
cache:
  yarn: true
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: Bv7/vVvZhLe+voMtrjMbxmM8d4bM1F4asYfUEreRiFeLeuys9F6sfE6gTHcWcnGGHET3Z8KN+Tr0rRxkcuVP41zdMl24LZxeI31RWQYdLdp6mn+rZ9qFKLlaSlfESQ0DGB4JvZKVwE3XRWjJdcA+v5rYtFs686eseMyXihqzJhBGwlCRo+BqzRbpHjuuqPXFNmdhVAn+Io0lWV8zo2FhOY6A4EQbaT5W9ocOC4o3BKow4NyYIXbOp8hQwrZRyM+52KUVkCEP0veOCVXJ1TUit0FjcrN3qPjy3K2cSghIepkt6ZPE7fmNL8k0IETVhHu8pIXUt1rRKMfycwj53NcHqh4OpQ4tZ4htFc4Erv43T3PNgjcAkiQDAxCn/kTlfdmQEDIyMrEESmHpmaSR6732eLnOsqeGbP+6zT7lcK5bAcLxQuu1Km7A7ZGo+o9yk8uL/R3gt+URW4O1Wxjjgy6JpzwIqS+u1WRhectpdyLgg5LKcYcoN+l3JOPQuSCw9FU+DolOTi4u3xk2abb/lmzN4uS73ILbskf/ylt54bd7EBIj6KvWl+gwmIxt8/B2/PmumPR31hRkxlRobEdw3sXagnxSpUXrImz9y30wL00fa/gkItfPxt0g/gIGrm+iAhsi4J/ZnO1qUQ7ndPdowTkj1vn+eBzeRmISAaOTZg1pdns=
deploy:
  provider: npm
  email: deptno@gmail.com
  skip_cleanup: true
  api_key:
    secure: UCqlEp5Fhcc8VsDOwUpKj4urKX/XRIqVQQMrHZ+CpDrBIOgK9g0hdTdV3UgtEw8/cMsmRgHyqbosMW3XHmS/PxMTbEtmhM6gyj6bStkpBZ1Ssqqv8vWfOkGBIj7EF3VIfFhsmv80x8K4qJCe3lsspf5gAhR0GRzA2Z5INmDyMpvt8CLld/RAMHdwXvhoq3LjAhLjeXfzrkxEfSUtarwHGGnw7oGoVwJpq0rJXKqCs0/KEZXIrxTyr0MqY40Ant13SwQSDxzyDGklKPizwgVBQAo7VcGKVLc0FksBxd2LebhkIoR3Ii67V0CxED9hhupsBKXHXr8UkCfbfpz7jle5rnDc5ZdWTmGR89GmO2LYx6VG2dPpM7PWFz6NYY+LDgbIJbRpYqX9/e2tl7kCZ88j2doPmp6v0iXM8URPnc8gVIXprnG6vm7zCLHUB270+jqVe7iEuhkM8uEVO662PvQ6rd57oGjM9siI4W3v//YZU9jN5C+KOM3uRbXW54rRs9Kmjc56daI047WnWVpWmD2wNME93eSdKqbchdOUiShfKz4iUMkge+ZuAHH8nJk0ufF+1bguF9agSkomCpSQaIxTEg2pEn8qIj9Y/JeXb5jrdCKRgNkzwr0FtPlIx02jT8sEI1RHuQnmGfgp3hBGtaGN8XxOuYHieha0qZpo/eHoSg=
